### ISSUE TITLE
Anleitung nicht kompatibel mit neuer Keycloak Version (v26)

### ISSUE THREAD

**Issue by Nobodi99** [it-at-m/ELSTER_NEZO_Plugin#6]
Die derzeitige Anleitung zum Thema "Deployment" ist leider nicht mit der aktuellen v26 von Keycloak kompatibel.

Die jar Datei muss in den Ordner "Providers" geschoben werden.

Leider habe ich noch nicht herausgefunden wie der Schritt mit den Themes umzusetzen ist, da der "Themes"-Ordner in der neuen Version leider leer ist.

Gibt es hierfür eine aktuelle Anleitung oder ist das Plugin nicht mehr notwendig?
Falls das Plugin obsolete ist, gibt es irgendwo eine Anleitung wie die Einrichtung jetzt funktioniert?

Mir wurde vom MUK-Support leider nur dieses Repository verlinkt.

**Comment by rowe42** [comment]
Die Quarkus-basierte Keycloak-Version benötigt das Plugin nicht mehr, da ist eine direkte Anbindung an NEZO mit Bordmitteln realisierbar.

Mir ist dabei keine explizite Schritt-für-Schritt-Anleitung bekannt. Ist aber im Grunde eine Standard-Anbindung eines per Brokering angebundenen SAML-Providers. 

Einziger Knackpunkt ist die `Unternehmensanschrift`, da muss der `XPath Attribute Importer` zum Einsatz kommen, hier ein Beispiel:
![image](https://github.com/user-attachments/assets/775dbc20-8405-4bd0-a91d-2e15e27c3327)

Ich hoffe das hilft weiter.
